### ISSUE TITLE
zine v0.13.0 reports error for basic `quote` block

### ISSUE THREAD

**Issue by zhongsp** [zineland/zine#209]
Installed the latest Zine lib:

```
$ cargo install zine
    Updating crates.io index
     Ignored package `zine v0.13.0` is already installed, use --force to override
```

Given a basic quote block from official doc:

```txt
```quote
author = "x"
bio = "y"
content = "z"
```

Run `zine serve`, an error occurred:

```
SZHONG@DTCN3053 MINGW64 /c/GitHub_Beckman/szhong-cloud-newsletter/newsletter (main)
$ zine serve
listening on http://127.0.0.1:3000
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Parse quote block error: missing field `content` at line 1 column 1', C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\zine-0.13.0\src\code_blocks\mod.rs:92:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Watch build error: task 10 panicked
```

If remove the `quote` block it works again.

**Comment by zhongsp** [comment]
I'm sure the format is correct and has a `content` field as described in issue description.

**Comment by zhongsp** [comment]
It's working on Ubuntu but on Windows 10 🙃

**Comment by eyeforyangon-hue** [comment]
> ကျွန်တော့်ကုဒ်က လပေါင်းများစွာကတည်းက အလုပ်လုပ်ပေမယ့် zine v0.13.0 ကို install လုပ်ပြီးတဲ့နောက်မှာ အလုပ်မလုပ်တာကြောင့် regression ပြဿနာလို့ ထင်ပါတယ်။
> 
> နောက်ဆုံးထွက် Zine lib ကို install လုပ်လိုက်ပါပြီ-
> 
> ```
> $ cargo install zine
>     Updating crates.io index
>      Ignored package `zine v0.13.0` is already installed, use --force to override
> ```
> 
> တရားဝင်စာရွက်စာတမ်းမှ အခြေခံကိုးကားချက်တစ်ခုကို ပေးထားသည်-
> 
> ```quote
> author = "x"
> bio = "y"
> content = "z"
> လုပ်ဆောင်ပါ `zine serve`၊ အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်-
> 
> ```
> $ zine serve
> listening on http://127.0.0.1:3000
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Parse quote block error: missing field `content` at line 1 column 1', C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\zine-0.13.0\src\code_blocks\mod.rs:92:53
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Watch build error: task 10 panicked
> ```
> 
> ပိတ်ဆို့တာ ကို ဖယ်ရှားလိုက်ရင် `quote`ပြန်အလုပ်လုပ်ပါတယ်။
